### ISSUE TITLE
Create checklist for instructor training events

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/site#1189]
Originated at https://github.com/swcarpentry/instructor-training/issues/20 from @jduckles: we need a checklist for both in-person and online instructor training events.

## Scheduling Event
- [ ] - Set a date
- [ ] - Decide if it will be online or in person
- [ ] - If in-person book travel
- [ ] - meet with host to talk through expectations
- [ ] - make sure host has identified attendees and delivered their names
- [ ] - send email to attendees with background reading and homework assignments 

## Running event 
- [ ] - test video conference link

## Post event
- [ ] - Email attendees about final project requirements
- [ ] - Schedule certifications (3-min lesson online)
- [ ] - Make sure AMY records are filled in
- [ ] - Badge instructors in AMY
- [ ] - Follow up with attendees not badged one month after
- [ ] - Follow up with attendees not badged two months after

**Comment by gvwilson** [comment]
Relocated to https://github.com/swcarpentry/website/issues/102
